# Tensors

A tensor is a generalisation of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes. They are fundamental aspect of TensorFlow. They are the main objects that are passed around and manipulated throughout the program. Each tensor represents a partial defines computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objevts that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape.

# Creating Tensors

In [1]:
# Imports

import tensorflow as tf

In [3]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

## Rank/Degree of Tensors

Mean the number of dimensions involved in the tensor. What we created abopve is a tensor of ank 0, known as a scalar (one value).

Below are tensors of higher degrees/ranks

In [9]:
rank1_tensor = tf.Variable(["Test", "Ok"], tf.string)
rank2_tensor = tf.Variable([["test", "ok","yeh"], ["test", "yes",  "yeh"]], tf.string)
rank3_tensor = tf.Variable([[["Test", "ok","yeh"],["Test", "ok","yeh"]], [["Test", "ok","yeh"],["Test", "ok","yeh"]]], tf.string)

## To determine the rank of a tensor we use

In [10]:
tf.rank(rank3_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

## Shape of Tensors

The shape of a tensor is the amount of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.

In [12]:
rank3_tensor.shape

TensorShape([2, 2, 3])

## Changing Shape

The number of elements of a tensor is the product of the size of all its shapes.
Often there are many shapes that have the same number of elemets, which make it convenient to change the shape of the tensor.

In [ ]:
tensor1 = tf.ones([1,2,3])            # tf.ones creates a shape [ 1,2,3] tensor which is full of ones
tensor2 = tf.reshape(tensor1,[2,3,1]) # rehsape existing data to specified shape
tensor3= tf.reshape(tensor2,[3,-1])    # -1 tells the tensor to calculate the size of the dimension in that place
                                      # This will reshape the tensor to [3,2]

# The number of elements in the reshape tensor MUST match the number in the original

In [17]:
print(tensor1)
print(tensor2)
print(tensor3)


tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Types of Tensors

### Different types of tensors
* Variable
* Constant
* Placeholder
* SparseTensor

With the exception of Variables all these tensors are immutable, meaning their value may not change during execution.

## Evaluating Tensors

Evaluate as in get its value. Since tensors represent a partially complete computation we will sometimes need to run what's called a session to evaluate the tensor

There are many ways to achieve this (will find out), below is the simplest way.

In [19]:
with tf.session() as sess: # creates a session using the default graph
    tensor.eval()          # tensor will ofcourse be the name of your tensor

AttributeError: module 'tensorflow' has no attribute 'session'

In the code above the tensor variable that was stored in the default graph is evaluated. The default graph holds all operations not specified to any other graph. It is possible to create our own seperate graphs but for now we will stick with the default.

## Reshaping Examples

In [25]:
#%tensorflow_version 2.x
print(tf.version)

t = tf.zeros([5,5,5,5])

t  = tf.reshape(t,[125, -1])
print(t)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\karab\\AppData\\Roaming\\Python\\Python311\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0